# Generated by Django 3.0.4 on 2020-07-03 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0006_applicant_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'OTHER')], max_length=10)),
                ('current_address', models.CharField(blank=True, max_length=500, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=500, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('languages', models.CharField(blank=True, max_length=500, null=True)),
                ('Hobbies', models.CharField(blank=True, max_length=500, null=True)),
                ('martial_status', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_no', models.BigIntegerField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=500, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('training_and_certification', models.CharField(blank=True, max_length=500, null=True)),
                ('experience', models.CharField(blank=True, max_length=500, null=True)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('project_link', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserEducationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(blank=True, max_length=250, null=True)),
                ('percentage_or_gpa', models.CharField(blank=True, max_length=10, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Resume')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
