# Generated by Django 3.0.4 on 2020-07-04 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20200703_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='user',
        ),
    ]
