# Generated by Django 3.0.4 on 2020-07-07 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0011_auto_20200707_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='jobdetail',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', related_query_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
