# Generated by Django 3.0.4 on 2020-07-07 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_auto_20200707_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
